#!/bin/bash
#@(#) use pandoc(1) to create man-pages.
###############################################################################
header(){
cat <<EOF
." Text automatically generated by panman.sh
.TH "$SHORTNAME" "3" "$(date +'%B %d, %Y')" "" "" " "
." -----------------------------------------------------------------
." * set default formatting
." disable hyphenation
.nh
." disable justification (adjust text to left margin only)
.ad l
." set smaller margin and spacing options
.ta T 0.2i
.nr IN 0.2i
." -----------------------------------------------------------------
EOF
}
###############################################################################
#set -x
source $(dirname $0)/sourceme.sh

cd $INTRINSICS
mkdir -p $BASE/man/man3 $BASE/man/cat3
for NAME in *.md
do
   case "$NAME" in
   *_index.md) ;;
   index.md) ;;
   XXGNU_Free_Documentation_License.md) ;;
   *)
      SHORTNAME=$(basename $NAME .md)
      SHORTNAME=${SHORTNAME,,}
      echo "NAME: $NAME to $SHORTNAME"

      ######################################################
      # man-pages
      (
         header
         sed -n -e '\%^##%,${ p }'  $NAME |
            pandoc -f commonmark -t man --columns=72
      )>$BASE/man/man3/$SHORTNAME.3fortran
      sed -i -r 's/(\.SS \\f\[B\])(.*)(\\f.*)/\1\U\2\E\3/' $BASE/man/man3/$SHORTNAME.3fortran
      sed -i -r 's/(\.SS \\f\[B\])(.*)(\\f.*)/.SH \U\2/' $BASE/man/man3/$SHORTNAME.3fortran
      gzip --force $BASE/man/man3/$SHORTNAME.3fortran
      ######################################################
      (
         sed -n -e '\%^##%,${ p }'  $NAME |
            pandoc -f markdown_mmd -t plain --columns=72 |
	    # remove trailing whitespace
	    sed -e 's/ *$//' |
	    # delete blank lines at top of file
	    awk 'NF {f=1} f' |
	    # get rid of artifact from converting from markdown
	    grep -v '^-$' |
	    cat -s
      )>$BASE/man/cat3/$SHORTNAME.3fortran
   ;;
   esac
done

# removes the other directories ??????????
cd $BASE/man
mandb -c .
env MANWIDTH=256 man --manpath=$BASE/man -k .|col -b
env MANWIDTH=80  man --manpath=$BASE/man --regex '.*'|
    col -b |
    expand --tabs=3 |
    tee /tmp/panman.out
################################################################################
cd $BASE 
tar cvfz docs/fortran.tgz man
################################################################################
build_module.sh > $BASE/src/M_intrinsics.f90
################################################################################
exit
################################################################################
